USVM API implementation for TypeScript
UnitTestBot/usvm pull request #195
Opened 2024-07-12 14:41 UTC by zishkaz

Basic USVM API implementation for futher development

2024-07-16 08:09 UTC, CaelmBleidd requested changes

2024-07-16 08:09 UTC, CaelmBleidd commented on usvm-ts/src/main/kotlin/org/usvm/TSInterpreter.kt
> +            val params = method.parameters.mapIndexed { idx, _ ->
Can be replaced with initializer

2024-07-16 08:09 UTC, CaelmBleidd commented on usvm-ts/src/main/kotlin/org/usvm/TSMachine.kt
> +                }.toSet() + methods
This code doesn't make sense

2024-07-16 08:09 UTC, CaelmBleidd commented on usvm-ts/src/main/kotlin/org/usvm/TSMachine.kt
> +            { loopTracker }
We are not sure about loop tracker, lets not include so complicated parts in the initial commits

2024-07-16 08:09 UTC, CaelmBleidd commented on usvm-ts/src/main/kotlin/org/usvm/TSMachine.kt
> +    private fun transparentCfgStatistics() = object : CfgStatistics<EtsMethod, EtsStmt> {
Transparent statistic has no purpose in the ts code rn

2024-07-16 08:09 UTC, CaelmBleidd commented on usvm-ts/src/main/kotlin/org/usvm/state/TSState.kt
> +import org.usvm.*
No asterisk

2024-07-16 08:09 UTC, CaelmBleidd commented on usvm-ts/src/test/kotlin/org/usvm/util/TSTestResolver.kt
> +        return TSTest(emptyList(), null)
Lets keep not implemented things with todos

2024-07-16 08:09 UTC, CaelmBleidd commented on usvm-ts/src/test/resources/ir/MinValue.json
> +{
Its ok for now, but I don't want to have these jsons in the repository in the main branch. It should be replaced with jacodb automatic solution

2024-07-16 08:29 UTC, Lipen commented on usvm-ts/build.gradle.kts
> +    api("org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.7")
See https://github.com/UnitTestBot/usvm/pull/190

2024-07-18 12:14 UTC, CaelmBleidd approved these changes

2024-07-18 12:14 UTC, merged