First step in supporting type inference, based on the usage of `sq_concat`
UnitTestBot/usvm pull request #207
Opened 2024-08-12 13:56 UTC by jefremof

2024-08-12 14:11 UTC, tochilinak requested changes

2024-08-12 14:11 UTC, tochilinak commented on usvm-python/usvm-python-main/src/main/kotlin/org/usvm/machine/interpreters/symbolic/operations/basic/MethodNotifications.kt
> +    pyAssert(context, context.ctx.mkImplies(nbAdd.not(), sqConcat))
`context.ctx.mkImplies(nbAdd.not(), sqConcat)` -> `nbAdd.not() implies sqConcat`

2024-08-12 14:11 UTC, tochilinak commented on usvm-python/usvm-python-main/src/main/kotlin/org/usvm/machine/interpreters/symbolic/operations/basic/MethodNotifications.kt
> +    pyAssert(context, context.ctx.mkImplies(nbAdd.not(), sqConcat))
Please add comment that describes the logic behind these changes.

2024-08-12 14:11 UTC, tochilinak commented on usvm-python/usvm-python-main/src/main/kotlin/org/usvm/machine/interpreters/symbolic/operations/basic/MethodNotifications.kt
> +    pyAssert(context, context.ctx.mkImplies(nbAdd.not(), sqConcat))
Also, please add the method that catches the event of `sqConcat` (similar to `nbAdd`). In that method, add constraint that operands have `sq_concat` method. In some cases, execution might skip `nbAdd` and go straight to `sqConcat`, but we still need to fix that operands have this method.

2024-08-13 09:13 UTC, tochilinak commented on usvm-python/usvm-python-main/src/main/kotlin/org/usvm/machine/interpreters/symbolic/operations/basic/MethodNotifications.kt
> +    two possible options.
Also, please add the following:

```
Moreover, for now it was decided, that operation `sq_concat` makes sense only in the situation, when both operands have the corresponding slot.
```

2024-08-14 06:23 UTC, tochilinak approved these changes

2024-08-16 08:40 UTC, sergeypospelov approved these changes

2024-08-16 08:45 UTC, merged