Type inference
UnitTestBot/usvm pull request #233
Opened 2024-12-25 20:30 UTC by Lipen

This PR adds monumental work on the IFDS-based type inference engine.

2024-12-26 23:16 UTC, Lipen commented
> Please, review detekt issues

@Saloed I have fixed some of them, but not all 300+.

2024-12-27 12:05 UTC, CaelmBleidd requested changes

2024-12-27 12:05 UTC, CaelmBleidd commented on usvm-dataflow-ts/src/main/kotlin/org/usvm/dataflow/ts/infer/EntryPointsProcessor.kt
> +            allMethods = scene.projectAndSdkClasses.flatMap { it.methods },
Use project files only

2024-12-27 12:05 UTC, CaelmBleidd commented on usvm-dataflow-ts/src/main/kotlin/org/usvm/dataflow/ts/infer/TypeInferenceResult.kt
> +                result.computeIfAbsent(it.name) { hashSetOf() }.add(clazz)
Doesn't work for dflt

2024-12-27 12:31 UTC, Lipen commented on usvm-dataflow-ts/src/main/kotlin/org/usvm/dataflow/ts/infer/verify/EntityId.kt
> +            : this(MethodId(methodSignature))
Fixed all formatting

2024-12-27 14:20 UTC, CaelmBleidd approved these changes

2024-12-27 14:21 UTC, merged